name: Wordsmoke
options:
  bundleIdPrefix: org.akuaku
  deploymentTarget:
    iOS: "26.0"
settings:
  SWIFT_VERSION: "6.2"
  DEVELOPMENT_TEAM: "8U7J5S7RGC"
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  SWIFT_GENERATE_STRINGS_FILE: YES
packages:
  Amplitude-Swift:
    url: https://github.com/amplitude/Amplitude-Swift
    branch: main
targets:
  Wordsmoke:
    type: application
    platform: iOS
    sources: [Wordsmoke]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.akuaku.playwordsmoke
      CODE_SIGN_ENTITLEMENTS: Wordsmoke/Wordsmoke.entitlements
    info:
      path: Wordsmoke/Info.plist
      properties:
        CFBundleDisplayName: Wordsmoke
        CFBundleIdentifier: org.akuaku.playwordsmoke
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    scheme:
      testTargets:
        - WordsmokeTests
        - WordsmokeUITests
    dependencies:
      - package: Amplitude-Swift
        product: AmplitudeSwift
  WordsmokeTests:
    type: bundle.unit-test
    platform: iOS
    sources: [WordsmokeTests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Wordsmoke
  WordsmokeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [WordsmokeUITests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Wordsmoke
  WordsmokeLocalUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [WordsmokeLocalUITests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Wordsmoke

schemes:
  WordsmokeLocalUITests:
    build:
      targets:
        Wordsmoke: all
    test:
      targets:
        - WordsmokeLocalUITests
      environmentVariables:
        WORDSMOKE_TEST_ADMIN_TOKEN: "__TEST_ADMIN_TOKEN__"
