name: Wordsmoke
options:
  bundleIdPrefix: org.akuaku
  deploymentTarget:
    iOS: "26.0"
settings:
  SWIFT_VERSION: "6.2"
  DEVELOPMENT_TEAM: "8U7J5S7RGC"
  ENABLE_USER_SCRIPT_SANDBOXING: YES
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  SWIFT_GENERATE_STRINGS_FILE: YES
  STRING_CATALOG_GENERATE_SYMBOLS: YES
packages:
  Amplitude-Swift:
    url: https://github.com/amplitude/Amplitude-Swift
    branch: main
  sentry-cocoa:
    url: https://github.com/getsentry/sentry-cocoa/
    from: 8.0.0
targets:
  Wordsmoke:
    type: application
    platform: iOS
    sources: [Wordsmoke]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.akuaku.playwordsmoke
        CODE_SIGN_ENTITLEMENTS: Wordsmoke/Wordsmoke.entitlements
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ENABLE_USER_SCRIPT_SANDBOXING: NO
    info:
      path: Wordsmoke/Info.plist
      properties:
        CFBundleDisplayName: Wordsmoke
        CFBundleIdentifier: org.akuaku.playwordsmoke
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        ITSAppUsesNonExemptEncryption: false
        NSGKFriendListUsageDescription: Wordsmoke uses your Game Center friends list to let you invite people you know.
    scheme:
      environmentVariables:
        WORDSMOKE_TEST_ADMIN_TOKEN: "iueyrhsdf"
        WORDSMOKE_DEBUG_MATCHMAKING_TOKEN: ihsdfs8
      testTargets:
        - WordsmokeTests
        - WordsmokeUITests
    dependencies:
      - package: Amplitude-Swift
        product: AmplitudeSwift
      - package: sentry-cocoa
        product: Sentry
    postBuildScripts:
      - name: Upload Debug Symbols to Sentry
        runOnlyWhenInstalling: true
        basedOnDependencyAnalysis: false
        inputFiles:
          - "$(DWARF_DSYM_FOLDER_PATH)/$(DWARF_DSYM_FILE_NAME)/Contents/Resources/DWARF/$(TARGET_NAME)"
        script: |
          # This script is responsible for uploading debug symbols and source context for Sentry.
          if which sentry-cli >/dev/null; then
            export SENTRY_ORG=akuaku
            export SENTRY_PROJECT=apple-ios
            ERROR=$(sentry-cli debug-files upload --include-sources "$DWARF_DSYM_FOLDER_PATH" 2>&1 >/dev/null)
            if [ ! $? -eq 0 ]; then
              echo "warning: sentry-cli - $ERROR"
            fi
          else
            echo "warning: sentry-cli not installed, download from https://github.com/getsentry/sentry-cli/releases"
          fi
  WordsmokeTests:
    type: bundle.unit-test
    platform: iOS
    sources: [WordsmokeTests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Wordsmoke
  WordsmokeUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [WordsmokeUITests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Wordsmoke
  WordsmokeLocalUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: [WordsmokeLocalUITests]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: Wordsmoke

schemes:
  WordsmokeLocalUITests:
    build:
      targets:
        Wordsmoke: all
    test:
      targets:
        - WordsmokeLocalUITests
      environmentVariables:
        WORDSMOKE_TEST_ADMIN_TOKEN: "iueyrhsdf"
        WORDSMOKE_DEBUG_MATCHMAKING_TOKEN: "ihsdfs8"
